name: proton-lumo-ai
summary: Private AI assistant powered by Proton Lumo
description: |
  Unofficial desktop app for Proton's Lumo.ai, providing a native Linux
  experience with system tray integration, keyboard shortcuts, and
  offline detection.

  Features:
  - System tray with show/hide toggle
  - Optional autostart on login
  - Ctrl+/- zoom controls
  - Offline detection with automatic reconnection
  - External links open in your default browser

  This is an unofficial community project and is not affiliated with
  Proton AG.

adopt-info: lumo-ai
grade: stable
confinement: strict
base: core24
contact: https://github.com/kenvandine/proton-lumo-ai/issues
issues: https://github.com/kenvandine/proton-lumo-ai/issues
website: https://github.com/kenvandine/proton-lumo-ai
license: GPL-3.0+
icon: ./assets/img/icon.png

platforms:
  amd64:
  arm64:
compression: lzo

parts:
  lumo-ai:
    plugin: nil
    source: .
    build-packages:
      - npm
      - git
    override-pull: |
      craftctl default
      VERSION=$(git describe --tags --abbrev=10 2>/dev/null || echo "0.0.1")
      craftctl set version=$VERSION
      sed -i.bak -e "s|@@VERSION@@|$VERSION|g" $CRAFT_PART_SRC/package.json
    override-build: |
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/unpacked
      cp $SNAPCRAFT_PROJECT_DIR/com.github.kenvandine.lumo.ai.desktop $SNAPCRAFT_PART_INSTALL/
      cp $SNAPCRAFT_PROJECT_DIR/assets/img/icon.png $SNAPCRAFT_PART_INSTALL/
      mv dist/linux*-unpacked/* $SNAPCRAFT_PART_INSTALL/unpacked 
      cp $SNAPCRAFT_PROJECT_DIR/com.github.kenvandine.lumo.ai-autostart.desktop $SNAPCRAFT_PART_INSTALL/
    prime:
      - com.github.kenvandine.lumo.ai*.desktop
      - unpacked
      - -*/assets/img/icon.png
      - -*/chrome-sandbox
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/include

  launcher:
    plugin: dump
    source: launcher
    override-build: |
      cp launcher $CRAFT_PART_INSTALL/

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  proton-lumo-ai:
    extensions: [gnome]
    desktop: com.github.kenvandine.lumo.ai.desktop
    autostart: proton-lumo.ai.desktop
    command: launcher
    plugs:
      - audio-playback
      - audio-record
      - home
      - network
      - shmem
      - unity7
    environment:
      GTK_USE_PORTAL: 1
      TMPDIR: $XDG_RUNTIME_DIR
      HOME: $SNAP_REAL_HOME
